version: "2"
services:
  sidekiq: &base
    build:
      context: .
      dockerfile: Dockerfile
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/api
      - bundle:/usr/local/bundle
    env_file:
      - .env
    links:
      - postgres
      - redis
  postgres:
    image: postgres:9.6
    environment:
      - PGUSER=postgres
      - PGDATABASE=api
      - PGHOST=postgres
    ports:
      - "1213:5432"
  web:
    tty: true
    stdin_open: true
    <<: *base
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
volumes:
  bundle:
